name: FollowingDependencyApp 
options:
  bundleIdPrefix: net.chigita
  deploymentTarget:
    iOS: "13.0"
  carthageExecutablePath: mint run Carthage/Carthage
targets:
  FollowingDependencyApp:
    info:
      path: followingDependencyApp/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "13.0"
    sources: 
      - path: followingDependencyApp
    dependencies:
      - carthage: Swinject
